name: Quasar Build
description: Install, lint, test and build a Quasar application.

runs:
  using: composite

  steps:
  - name: Install dependencies
    run: npm ci
    shell: bash

  - name: Lint files
    run: npm run lint
    shell: bash

#   - name: Test application
#     run: npm run test:ci
#     shell: bash

  - name: Build
    run: npm run build
    shell: bash
